user_name = input('enter your name:')
print ('hello,', user_name)
user_age = input('how old are you')
user_age= int(user_age)
print ('Your age is', user_age)
user_live= input('Where do you live?')
print ('You live in', user_live)